# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"LinearRegression": "01_linear_regression.ipynb",
         "fit": "01_linear_regression.ipynb",
         "fit2": "01_linear_regression.ipynb",
         "GeneralFit": "01_linear_regression.ipynb"}

modules = ["n01.py"]

doc_url = "https://mnpinto.github.io/learn_ai_today/"

git_url = "https://github.com/mnpinto/learn_ai_today/tree/master/"

def custom_doc_links(name): return None
